app:
  enabled: false

worker:
  env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: urunan-service-dev
          key: DATABASE_URL
    - name: PERFORM_MIGRATIONS
      valueFrom:
        secretKeyRef:
          name: urunan-service-dev
          key: PERFORM_MIGRATIONS
    - name: KAFKA_BROKER
      valueFrom:
        secretKeyRef:
          name: urunan-service-dev
          key: KAFKA_BROKER
    - name: KAFKA_USERNAME
      valueFrom:
        secretKeyRef:
          name: urunan-service-dev
          key: KAFKA_USERNAME
    - name: KAFKA_PASSWORD
      valueFrom:
        secretKeyRef:
          name: urunan-service-dev
          key: KAFKA_PASSWORD
    - name: HOSTNAME
      valueFrom:
        secretKeyRef:
          name: urunan-service-dev
          key: HOSTNAME
  enabled: true

  liveness:
    enabled: false

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi


migration:
  enabled: false

ingress:
  enabled: false

virtualService:
  enabled: false

users:
  - lukluk
  - abdul.azis
